# -*- coding: utf-8 -*-
"""RAG_LLMOPS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Sh7atH4NEHFhGBYe3oh9CeFpXUQ2fZl
"""

!nvidia-smi

!pip install langchain

!pip install langchain_community

!pip install langchain_text_splitter
!pip install langchain_chroma
!pip install langchain_groq

import os
from langchain_community.document_loaders import UnstructuredFileIOLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_community.embeddings import HuggingFaceBgeEmbeddings
from langchain_chroma import Chroma
from langchain_groq import ChatGroq
from langchain_classic.chains import RetrievalQA

# Import userdata to access secrets
from google.colab import userdata

# Retrieve the GROQ API key from Colab secrets
os.environ["GROQ_API_Key"] = userdata.get('GROQ_API_Key')
os.environ["LANGSMITH_API_KEY"] = userdata.get('LANGSMITH_API_KEY')

import requests
url="https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-python?pivots=python-mode-decorators.pdf"
response=requests.get(url)
with open("Azure Functions developer reference guide for Python apps.pdf","wb") as f:
  f.write(response.content)

!pip install langsmith

import os
from langsmith import Client
os.environ["LANGCHAIN_TRACING_V2"]="true"
os.environ["LANGCHAIN_PROJECT"]="RAG_LLMOPS_PROJECT"
print('Lansmith tracing enabled')

!pip install 'unstructured[pdf]'

with open("Azure Functions developer reference guide for Python apps.pdf", "rb") as f:
    loader=UnstructuredFileIOLoader(f)

text_splitter=CharacterTextSplitter(chunk_size=2000,chunk_overlap=400)

with open("Azure Functions developer reference guide for Python apps.pdf", "rb") as f:
    # Re-instantiate the loader with the open file object to ensure it's accessible
    file_loader = UnstructuredFileIOLoader(f)
    document = file_loader.load()

# Split the documents first
texts = text_splitter.split_documents(document)

# Now add the source to the metadata of each split document (chunk)
pdf_filename = "Azure Functions developer reference guide for Python apps.pdf"
for doc in texts:
    doc.metadata['source'] = pdf_filename

type(texts)

texts[2]

embeddings=HuggingFaceBgeEmbeddings()

persist_directory='vector_db'

from google.colab import userdata
os.environ["GROQ_API_Key"] = userdata.get('GROQ_API_Key')

from langchain_groq import ChatGroq
import os

# Ensure the API key is available in the environment before initializing ChatGroq
# Assuming GROQ_API_Key is set correctly in a previous cell like fed4e2cb or y23hTq6I_Rgd
llm=ChatGroq(model='llama-3.3-70b-versatile', temperature=2, api_key=os.environ.get('GROQ_API_Key'))

vectordb=Chroma.from_documents(documents=texts,embedding=embeddings,persist_directory=persist_directory)

retriever=vectordb.as_retriever()

qa_chain=RetrievalQA.from_chain_type(llm=llm,chain_type="stuff",retriever=retriever, return_source_documents=True)

query='what are the functions from pdf'
response=qa_chain.invoke({'query':query})
print(response['result'])

query='what are the python functions from pdf'
response=qa_chain.invoke({'query':query})
print(response['result'])

query='what are the deployment functions from pdf'
response=qa_chain.invoke({'query':query})
print(response['result'])

import gradio as gr

def chatbot_response(question):

  try:
    response=qa_chain.invoke({'query':question})
    answer=response['result']
    sources=[]
    for doc in response['source_documents']:
      if 'source' in doc.metadata:
        sources.append(doc.metadata['source']) # Corrected key to 'source'
    source_text='\n'.join(list(set(sources)))
    final_response=f"""
{answer}
\n\nSources:\n{source_text}""" # Closed the f-string and added source_text
    return final_response # Added return statement
  except Exception as e:
    return f"An error occurred: {e}"

demo=gr.Interface(fn=chatbot_response,
                  inputs=gr.Textbox(
                      lines=2,
                      placeholder='Ask questions from your pdf'),
                  outputs="text",
                  title="PDF Chatbot")

demo.launch(debug=True)